# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  deployMaster:
    docker:
      - image: circleci/node:8.9.0
    working_directory: ~/repo
    steps:
      - checkout
      # remove node_modules
      - run: rm -rf node_modules
      # install sshpass
      - run:
          name: install sshpass
          command: |
            sudo apt-get install sshpass
      - run:
          name: NPM Install
          command: npm install
      - run:
          name: running build 
          command: sudo npm run build
      - run:
          name: after build 
          command:  ls
      - run:
          name: show listings 
          command: cd build 
      - run:
          name: show listings 
          command:  ls
       
      # changing permission
      - run: chmod +x ./.circleci/deployDev.sh

      - add_ssh_keys:
          fingerprints:
            - "b7:4a:a3:e8:e5:b1:92:da:12:b6:04:7b:8a:97:c4:0c"

      # deploy and start server
      - run: ./.circleci/deployDev.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      # - test
      - deployMaster:
          # requires:
          #   - test
          filters:
            branches:
              only: dev